### ISSUE TITLE
Explanation of the table

### ISSUE THREAD

**Issue by ValCher1961** [jbsky/Debian-On-WRT1900AC-V1#1]
Hello Jbsky!
In your repository, I found a patch of power table for the WiFi - add_mamba_powertables.patch
You could have given a reference where to read or explain this table, and more the data array. I understand that the first value refers to the channel number, and what means the following values I don't understand.
`<4 0 0x16 0x15 0x14 0x13 0x12 0x11 0x10 0x9 0x8 0x7 0x6 0x5 0x4 0x3 0x2 0x0 0 0xf>`

I should be very grateful for the reference or explanation.

**Comment by jbsky** [comment]
Hi @ValCher1961 
 I tried to control the signal strength! I tested it, but it's not working. I feel like this table is not bringing anything. On the other hand, by compiling the controller, the maximum signal intensity can be set. 
http://networkgeekstuff.com/networking/how-to-create-custom-linux-wi-fi-regulatory-database-to-unlock-30db1000mw/

(Long live deepl! LOL)

**Comment by ValCher1961** [comment]
The thing is, I want to rein in wrt3200 released for the USA market. As you may know, it has a power table and the numbering of allowed channels built into the EEPROM, according to the rules of FCC.
I managed to deceive the Mwlwifi driver and remove the region-the FCC-US country, that is, reconfigure the region to ETSI and open channels 12 and 13, but the signal strength remains the same.
I want to try to play the values in the table to understand the force or not.

In general, I'll experiment.
Thank you for the link. :)

**Comment by jbsky** [comment]
So, for the table, I told myself like you that the first digit is necessarily the channel, then we have a suite that I thought maybe is an intensity. I tried a combination, but it has no effect, the signal is at its maximum whatever the number. I have the impression that the last few digits are somehow activated or deactivated. In any case, the iw wlan0 set txpower command has no effect. The only way to limit the signal is to recompile the regulatory database.

**Comment by ValCher1961** [comment]
Database take from CRDA and include in kernel?

**Comment by jbsky** [comment]
It can be included from the kernel, this is the CONFIG_CFG80211_INTERNAL_REGDB option to specify. But it could also be a separate compilation.

**Comment by ValCher1961** [comment]
I'm not strong at C, but you'll see in the Mwlwifi driver there is a DTS processing of the file for Powertabl  ( line 206-https://github.com/kaloz/mwlwifi/blob/master/core.c )

**Comment by jbsky** [comment]
Don't worry, I'm not strong either! I agree, the driver seems to put something in memory, but, personally, I didn't manage to play on the power of the signal except to limit it. I think the functionality is not implemented. After that, I may be wrong.

**Comment by ValCher1961** [comment]
I'm included in the CONFIG_CFG80211_INTERNAL_REGDB core,
And I'm going to check the ability to change the signal strength.
Thanks for the answers.
It's late, it's time to rest.

Good night.

**Comment by jbsky** [comment]
Before compiling your kernel, change your signal in the. /net/wireless/db. txt file. I just managed to limit the signal strength by changing the regulatory database, do we agree?

**Comment by ValCher1961** [comment]
Yes, I'll install a new database in the  db.txt file. As I understand it, it gives you the maximum allowed levels of signal, channel numbers, and DFS channels for regions. I'll announce the results tonight.

**Comment by ValCher1961** [comment]
Tried the edited table with the minimum values, but the driver ignores the power table from DTS.
The only thing the driver takes from a DTS table is the 'Marvell, 2 = <0>' or 'Marvell, 5 GHz = <0>', if they are not available, when viewing the information in 'iw phyX info' is displayed at the same time as Band1 and Band2.

In general, I'm still looking for where the Mwlwifi driver has a choice between a built-in and an external power table.

**Comment by jbsky** [comment]
I also spent a good part of the day searching through the code and putting wiphy_debug () from everywhere to try to understand the code. In fact, to fix the signal strength, there is necessarily a command that goes to the firmware. So, I searched by putting in the set and get txpower functions and there is something wrong with the code. Normally, the /sys/kernel/debug/ieee80211/phy1/mwlwifi/device_pwrtbl file should display the power table but this is not the case. I made a request to Yuhaurlin to find out if it was normal. I'm waiting for an answer.

**Comment by ValCher1961** [comment]
I don't have power in the /sys/kernel/debug/ieee80211/phy1/mwlwifi/device_pwrtbl , because I've cleared the region code check in the driver, and the driver thinks my map has world code. It gave me the freedom to change regions, but the power hasn't changed.

Well, let's wait for the answer Yuhhaurlin.

**Comment by jbsky** [comment]
The change in signal strength is not supported. However, changing the values in the table is supported. I think only the first value is used.
Using a value of 22 in hexadecimal, I have 35 for RSSI. With the default values, either 9, I have 47 or a poorer signal.
iw wlan set txpower... has no effect.

**Comment by ValCher1961** [comment]
Thanks Jbsky, I'll try.
I'm very tense that we can't change capacity within a given range of ETSI or FCC. I don't know what it's called, Marvell-Linksys policy or Yuhhaurlin position.

**Comment by jbsky** [comment]
If you want, I upload a patch to add debug messages.
Don't forget to enable the kernel options:

CONFIG_MAC80211_DEBUGFS=y
CONFIG_MAC80211_MESSAGE_TRACING_TRACING=y
CONFIG_MAC80211_DEBUG_MENU=y
' # CONFIG_MAC80211_NOINLINE is not set
CONFIG_MAC80211_VERBOSE_DEBUG=y
CONFIG_MAC80211_MLME_DEBUG=y
CONFIG_MAC80211_STA_DEBUG=y
CONFIG_MAC80211_HT_DEBUG=y
CONFIG_MAC80211_OCB_DEBUG=y
CONFIG_MAC80211_IBSS_DEBUG=y
CONFIG_MAC80211_PS_DEBUG=y
CONFIG_MAC80211_TDLS_DEBUG=y

They have no effect on wifi performance.

**Comment by ValCher1961** [comment]
Very good offer!
I'll be very grateful!

**Comment by ValCher1961** [comment]
By the way, this is the branch where our driver was discussed. It discovers some of the details of driver build and structure. Read the entire branch.
https://www.spinics.net/lists/linux-wireless/msg157416.html

**Comment by jbsky** [comment]
If it is possible to change the signal strength in the function: 
`static int mwl_mac80211_config (struct ieee80211_hw *hw, u32 change) `
in the mac80211.c file at the root of the mwlwifi project.

Indeed, I have added a `wiphy_debug(hw->wiphy, "Make a test", changed);` and actually I have something that displays when I execute `iw wlan1 set txpower fixed 100` with the `dmesg` command.
The flag to check if a change in signal strength is IEEE80211_CONF_CHANGE_POWER, but this must be checked.

**Comment by jbsky** [comment]
Please check the following patch: https://raw.githubusercontent.com/jbsky/Debian-On-WRT1900AC-V1/e9cf852b394a748a47033ddd7e453815a20dd530/kernel/patch/ability_to_change_the_signal_strength.patch
After a restart, check with the following command using Acrylic:
iw wlan1 set txpower fixed 3000
iw wlan1 set txpower fixed 100

It works for me with the wrt1900ac v1.

I haven't checked if the power table entered in the dts file has an impact on the result. But given the debugging in my own way, since I'm a novice, I don't think so, but that's to be checked. However, the variable should be partitioned so as not to allow a value greater than 30, see 40.

**Comment by jbsky** [comment]
Attention, the good file is https://raw.githubusercontent.com/jbsky/Debian-On-WRT1900AC-V1/e9cf852b394a748a47033ddd7e453815a20dd530/kernel/patch/ability_to_change_the_signal_strength.patch, to use with the original mwlwifi.

**Comment by ValCher1961** [comment]
Thanks, I'm going to try.
I'll let you know the results.

**Comment by ValCher1961** [comment]
I had a look at your code, and I realized that I had just seen these lines. We're going in parallel :)

**Comment by ValCher1961** [comment]
I don't have the power to change.
![image](https://user-images.githubusercontent.com/17226948/29936881-c4995d24-8e94-11e7-93e5-905b5f1cb7f4.PNG)

**Comment by ValCher1961** [comment]
Interestingly, immediately after the reboot, within 2 minutes the signal strength changes from-27 to-70 RSSI.

**Comment by jbsky** [comment]
Are you testing well on the WRT1900AC v1? As long as the power table is loaded from the dts, it should work. Try with iw wlan1 set txpower limit 2000 to see.

**Comment by ValCher1961** [comment]
I'm using wrt3200. I have not wrt1900.

**Comment by jbsky** [comment]
When you try to change the signal strength, by any chance, do you specify the right device?
Have you tried it with wlan0?
At home, I only use wlan1 which is the 5GHZ band.

**Comment by ValCher1961** [comment]
I'm trying to reduce power in the Wlan1 device 2,4 GHz, as I wrote, I have an American version of wrt3200. The permitted signal strength for devices 2,4 GHz-30dBm (ETSI-20dBm). That's why I want to loosen the force a little bit.
30dBm equals 1000 mW, I don't want to be in the microwave. :)

In large mega-cities, the range of 2,4 GHz is very overloaded and additional power will hurt all others. The increase in this range is justified only in country houses, where large areas and neighbors are far away.
